const constellationArray = [
    "andromeda",
    "aquarius",
    "aquila",
    "aries",
    "cancer",
    "canis-major",
    "centaurus",
    "corona-borealis",
    "crater",
    "crux",
    "cygnus",
    "draco",
    "gemini",
    "leo",
    "libra",
    "lyra",
    "orion",
    "pegasus",
    "pisces",
    "sagittarius",
    "scorpius",
    "taurus",
    "ursa-major",
    "ursa-minor",
    "virgo",
]

export default constellationArray;